name: Daily Scrape and Update Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: ⚙️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # <-- pytz هم نصب می‌شود

      - name: 🕸️ Run scraping script
        # اسکریپت را اجرا می‌کند تا پوشه و README ایجاد شود
        run: python scraper.py

      - name: 🔧 Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: ⬆️ Commit and Push Changes
        run: |
          # پوشه خروجی و فایل README.md را اضافه می‌کند
          git add output_configs/ README.md # <--- تغییر: README.md اضافه شد

          # بررسی می‌کند که آیا تغییری برای کامیت وجود دارد یا نه
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
          else
            echo "Changes detected. Committing and pushing..."
            # پیام کامیت را کمی تغییر می‌دهیم
            git commit -m "docs: Update README and config files 🤖 [skip ci]"
            git push
          fi
